databases:
  - name: shiva
    databaseName: shiva_4pgk
    user: shiva_4pgk_user

services:
  - type: web
    name: shiva
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: shiva_4pgk
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false